---
title: "Rerun DE analysis for four comparisons"
author: "Daisy Fu"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    code_folding: hide
    self_contained: yes
    toc: true
    toc_depth: 5
    toc_float:
      collapsed: true
      smooth_scroll: false
    number_sections: true
---

# Background

JIRA ticket number: VBCS-1202

There are 4 samples/group, 16 in total.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, warning=F, message=F, cache=F)
```

# Load packages


```{r load_libs, echo=TRUE, warning=F, message=F, cache=FALSE}

if (!"/varidata/research/projects/bbc/tools/Fu_R_4.4_ondemond_lib" %in% .libPaths()) {
  current_pathes <- .libPaths()
  .libPaths(c("/varidata/research/projects/bbc/tools/Fu_R_4.4_ondemond_lib", current_pathes))
}

orgdb <- "org.Mm.eg.db" 
FDR_thresh <- 0.1

library(orgdb, character.only=TRUE)
library(enrichplot)
library(tidyverse)
library(edgeR)
library(DESeq2)
library(cowplot)
library(RColorBrewer)
library(ggrepel)
library(EnhancedVolcano)
library(tidyverse)
library(readxl)
library(data.table)
library(openxlsx)
library(ComplexHeatmap)
library(kableExtra)
library(clusterProfiler)
library(rjson)

dir.create("data_save")
dir.create("res")

```

# Import counts and meta


```{r import_data}

dir.create("data_save")


# read in couts -----------------------------------------------------------
files <- list.files("../rnaseq_workflow/results/star/", pattern = "ReadsPerGene.out.tab", full.names = FALSE)
names(files) <- str_remove_all(files, ".ReadsPerGene.out.tab$")

salmon_lib_files <- list.files("../rnaseq_workflow/results/salmon/", pattern = "lib_format_counts.json", recursive=TRUE, full.names = TRUE)
lib_types <- unlist(lapply(salmon_lib_files, function(x) fromJSON(file=x)$expected_format))
lib_type <- unique(lib_types)

if(length(lib_type) > 1){
  stop("More than 1 library type detected.")
}

if(!lib_type %in% c("ISR", "SR", "ISF", "SF", "IU", "U")){
  stop("Unknown library type detected.")
}


counts_col <- case_when(
  lib_type %in% c("ISR", "SR") ~ 4,
  lib_type %in% c("ISF", "SF") ~ 3,
  lib_type %in% c("IU", "U") ~ 2,
  .default=999
)
stopifnot(counts_col %in% c(2, 3, 4))

dge <- edgeR::readDGE(files, path = "../rnaseq_workflow/results/star/", columns = c(1, counts_col), 
                      skip = 4, labels = names(files), header=FALSE)

raw_cts <- edgeR::getCounts(dge)
names(attributes(raw_cts)$dimnames) <- NULL

# follow the previous R markdown ------------------------------------------
ensembl_ids <- str_split_fixed(rownames(raw_cts), "\\.", 2)[, 1]
duplicated_genes <- rownames(counts)[duplicated(ensembl_ids)] ## this is null, no duplication of gene ensembl ID

## simply gene names:
rownames(raw_cts) <- str_split_fixed(rownames(raw_cts), "\\.", 2)[, 1]


gene_names_df <- data.frame(row.names = rownames(raw_cts))
gene_names_df$Symbol <- AnnotationDbi::mapIds(eval(as.name(orgdb)), 
                                              rownames(gene_names_df), 
                                              keytype="ENSEMBL", column="SYMBOL", 
                                              multiVals="first")

gene_names_df$Uniq_syms <- scater::uniquifyFeatureNames(rownames(gene_names_df),
                                                        gene_names_df$Symbol)
gene_names_df$entrez <- AnnotationDbi::mapIds(eval(as.name(orgdb)), rownames(gene_names_df), 
                                              keytype="ENSEMBL", column="ENTREZID", 
                                              multiVals="first") # there are duplicates in here.


meta_df <- read_excel("../meta file.xlsx") %>% 
  select(c("sample_ID", "Genotype", "Diet", "Sex")) %>%
  mutate(sample_ID =  gsub(" ", "", sample_ID)) 
meta_df$Genotype <- str_split_fixed(meta_df$Genotype, "\\/", 2)[, 1] 
meta_df <- meta_df %>%
  mutate(Geno_diet = paste0(Genotype, "_", Diet))

print(meta_df)

y <- DGEList(raw_cts, samples = meta_df, genes = gene_names_df, group = meta_df$Geno_diet) 

### filtering the low counts, 
keep <- rowSums(edgeR::cpm(y$counts) > 0.5) >= 4
table(keep) ## check how many genes will be kept and how many will be removed. 

y <- y[keep, , keep.lib.sizes=FALSE]
y <- calcNormFactors(y)

norm_counts <- edgeR::cpm(y, log=TRUE)

## export count data, which are normalized and CPM, note here, log transformation is log2 based. 
norm_counts_df <- y$genes %>% 
  rownames_to_column("ensembl_id") %>% 
  left_join(., as_tibble(norm_counts, rownames="ensembl_id"), by="ensembl_id") 

write_rds(norm_counts_df, paste0("data_save", "/","norm_counts.rds"))
write_tsv(norm_counts_df, paste0("data_save", "/","norm_counts.tsv"))

design <- model.matrix(~0+Geno_diet + Sex, data = y$samples) 

colnames(design) <- gsub("Geno_diet", "", colnames(design))
design

y <- estimateDisp(y, design, robust=TRUE)
#plotBCV(y, main=paste0("BCV plot"))

fit <- glmQLFit(y, design, robust=TRUE)
#plotQLDisp(fit, main=paste0("QLDisp plot"))


## also do a PCA 
dds = DESeqDataSetFromMatrix(countData = raw_cts,
                             colData = meta_df, design = ~ Geno_diet + Sex)

dim(dds)

vsdata <- vst(dds, blind=FALSE)
pca <- plotPCA(vsdata, intgroup=c("Diet", "Genotype", "Sex", "Geno_diet"), returnData = T)
percentVar <- round(100 * attr(pca, "percentVar"))


pca_plot <- ggplot(pca, aes(x = PC1, y = PC2, color = Geno_diet , shape = Sex, label = name)) +
  geom_point(size = 3) +
  theme_cowplot() +
  geom_text_repel(label = pca$name, size = 4, max.overlaps = Inf, show.legend = F) +
  xlab(paste0("PC1: ", percentVar[1], "% variance")) +
  ylab(paste0("PC2: ", percentVar[2], "% variance")) +
  scale_shape_discrete(name="") +
  scale_color_brewer(palette = "Dark2", name = "") 
pca_plot


## DE gene contrasts. 
contrasts_list <- list("KI_HFD-KI_Con.diet",
                       "KI_HFD-WT_HFD",
                       "KI_Con.diet-WT_Con.diet",
                       "WT_HFD-WT_Con.diet")

contrasts_list <- set_names(contrasts_list, nm = contrasts_list)

contrasts <- makeContrasts(contrasts=contrasts_list, levels=colnames(design))

contrasts


qlf <- lapply(rlang::set_names(colnames(contrasts), colnames(contrasts)), 
              function(contrast){
                glmQLFTest(fit, contrast=contrasts[,contrast])} )
res <- lapply(qlf, function(contrast) topTags(contrast, n = Inf))
save(y, qlf, fit, res, file = paste0("data_save", "/","edgeR", "_data_file.RData"))

lapply(qlf, function(x) {
  summary(decideTests(x, p.value = 0.1)) })     ### there are a few genes here. 


############## going over the results. 
DE_gene_by_lappy <- function(current_contrast) {
  qlf_current <- qlf[[current_contrast]]
  res_current <- res[[current_contrast]]
  toptags <- topTags(qlf_current, n = 10) %>% as.data.frame() %>% dplyr::select(!c(Uniq_syms, entrez))
  cat(paste0("Results of comparison ", current_contrast), sep = "\n\n")
  
  cat(paste0(" "), sep = "\n\n")
  cat(paste0("Number of DE genes: "), sep = "\n\n")
  DE_sum <- summary(decideTests(qlf_current, p.value = FDR_thresh))
  print(DE_sum)
  
  cat(paste0(" "), sep = "\n\n")
  cat(paste0("Top 10 DE genes sorted by corrected pvalue (FDR) "), sep = "\n\n")
  print(toptags)
  
     df_volcano <- res_current$table %>% 
    as.data.frame() %>%
              mutate(diffexpress = case_when(FDR < FDR_thresh & logFC > 0 ~ "DE_up", 
                                   FDR < FDR_thresh & logFC < 0 ~ "DE_down", 
                                   .default = "Not DE") %>% 
             factor(., levels = c("DE_up", "DE_down", "Not DE"))) %>%
    mutate(toptag_genes = case_when(rownames(.) %in% rownames(toptags) ~ Symbol,
                                    .default = ""))
  
  new_volcano <- 
    ggplot(data = df_volcano, 
           aes(x = logFC, y = -log10(FDR), col = diffexpress, label=toptag_genes)) +
    geom_vline(xintercept = c(-1, 1), col = "gray", linetype = 'dashed') +
    geom_hline(yintercept = -log10(0.05), col = "gray", linetype = 'dashed') +
    geom_point(size = 0.8) +
    scale_color_manual(values = c("DE_up" = "firebrick", 
                                  "DE_down" =  "blue", 
                                  "Not DE" = "grey50"), # to set the colours of our variable<br />
                       labels = c("Up-regulated", "Down-regulated", "Not DE")) + 
    geom_text_repel(size = 3, show.legend = FALSE, max.overlaps = Inf) +
    coord_cartesian(ylim = c(0, max(-log10(df_volcano$FDR))), xlim = c(-5, 5)) + 
    labs(color = '', 
         x = expression("log"[2]*"fold-change"), y = expression("-log"[10]*"FDR")) +
    ggtitle(paste0('Volcano plot of ', current_contrast)) +
    theme_cowplot()
  
  
  print(new_volcano)
 
  res_export <- res_current %>% as.data.frame(.) %>% rownames_to_column(., var = "ensembl_ID")
  
  write_tsv(res_export, file = paste0("res","/", "edgeR", "_", current_contrast, 
                                             "_DE_results.tsv"))  
}


```

# DE genes

## within KI, high vs. low fat diet

KI_HFD-KI_Con.diet

```{r comp1, fig.height= 5, fig.width=7, fig.align = 'center' }
DE_gene_by_lappy(current_contrast = contrasts_list[[1]])


```

## within HFD, KI vs. WT

KI_HFD-WT_HFD

```{r comp2, fig.height= 5, fig.width=7, fig.align = 'center' }
DE_gene_by_lappy(current_contrast = contrasts_list[[2]])


```

## within Con.diet, KI vs. WT
KI_Con.diet-WT_Con.diet

```{r comp3, fig.height= 5, fig.width=7, fig.align = 'center' }
DE_gene_by_lappy(current_contrast = contrasts_list[[3]])


```

## within WT, high vs. low fat diet. 
WT_HFD-WT_Con.diet
                   
```{r comp4, fig.height= 5, fig.width=7, fig.align = 'center' }
DE_gene_by_lappy(current_contrast = contrasts_list[[4]])

```





